module.exports = [
    "VivoCity",
    "ION Orchard",
    "Jewel Changi Airport",
    "NEX",
    "Tampines Mall",
    "Junction 8",
    "Plaza Singapura",
    "Bugis Junction",
    "Suntec City",
    "Orchard Central",
    "313@Somerset",
    "Raffles City Shopping Centre",
    "Marina Bay Sands",
    "Bedok Mall",
    "City Square Mall",
    "Parkway Parade",
    "The Clementi Mall",
    "Causeway Point",
    "Hougang Mall",
    "Waterway Point",
    "The Shoppes at Marina Bay Sands",
    "Tiong Bahru Plaza",
    "Northpoint City",
    "Jurong Point",
    "Changi City Point",
    "Lot One Shoppers' Mall",
    "Westgate",
    "Hillion Mall",
    "JEM",
    "Suntec City Mall",
    "One KM",
    "Rivervale Mall",
    "Liat Towers",
    "AMK Hub",
    "Compass One",
    "JCube",
    "IMM",
    "Great World City",
    "The Centrepoint",
    "Funan",
    "HDB Hub",
    "The Star Vista",
    "Clementi Mall",
    "Millenia Walk",
    "Square 2",
    "Changi Airport Terminal 3",
    "Chinatown Point",
    "The Seletar Mall",
    "Sembawang Shopping Centre",
    "Wisma Atria",
    "Anchorpoint",
    "Paragon",
    "Katong Shopping Centre",
    "Alexandra Retail Centre",
    "Causeway Point Shopping Centre",
    "Arcade @ The Capitol Kempinski",
    "Tanglin Mall",
    "The Poiz Centre",
    "Havelock II",
    "United Square Shopping Mall"]
  
